### ISSUE TITLE
Program crashes with error in rule 3 regardless of the rules file used

### ISSUE THREAD

**Issue by techsup** [PawelBoe/aclsim#1]
aclsim/bin> cat ../tests/asa-DMZ2_access_in.acl | grep -v remark | tr -s ' ' | cut -d' ' -f4- > ../tests/AIP-Rule1.txt
aclsim/bin> ./aclsim -f ../tests/AIP-Rule1.txt
tcp 141.33.207.12 1024 141.33.160.1 22
>>Error occured in rule 3
>>Terminating program ..

**Comment by PawelBoe** [comment]
Hi, can you give me the contents of "../tests/asa-DMZ2_access_in.acl"? Or some file that also produces this behavior? This way I can more easily trace down the cause of the bug. Will take a look at it this weekend ;)

**Comment by techsup** [comment]
Hi, the file is in the subdirectory tests of the tar file I gave to your father. Please note also the file exampleCall... (I don't remember the name exactly).

Kind regards,

André Saar 


André Saar, IT-Leiter
Leibniz-Institut für Astrophysik Potsdam (AIP)
An der Sternwarte 16
14482 Potsdam
———————————————
Vorstand: Prof. Dr. M. Steinmetz, Matthias Winker

Stiftung bürgerlichen Rechts
Stiftungsverzeichnis Brandenburg: 26 742-00/7026

**Comment by PawelBoe** [comment]
Hey again, I have rewritten the tool in c++ now.. I just could not stand my own c-code from over a year ago :D Right now I do not get any errors with the call that you showed me (and the file that I have gotten to test that). It does not support features like object-groups though.
